daemonset:
  enabled: true
  filebeatConfig:
    filebeat.yml: |
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  equals:
                    kubernetes.labels.app: merlot
                config:
                 - type: container
                   paths:
                     - /var/log/containers/*-${data.kubernetes.container.id}.log
                   multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
                   multiline.negate: true
                   multiline.match: after
                   processors:
                     - drop_fields:
                         fields: ["log", "input", "ecs", "host", "kubernetes"]

              - condition:
                  equals:
                    kubernetes.labels.app: stock-consumer
                config:
                  - type: container
                    paths:
                      - /var/log/containers/*-${data.kubernetes.container.id}.log
                    multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
                    multiline.negate: true
                    multiline.match: after
                    processors:
                      - drop_fields:
                          fields: ["log", "input", "ecs", "host", "kubernetes"]


      output.logstash:
        host: '${NODE_NAME}'
        hosts: ['198.19.212.36:5057']

deployment:
  enabled: false