apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.consumer.name}}
spec:
  replicas: {{ .Values.deploy.consumer.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.deploy.consumer.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.consumer.name}}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .Values.deploy.consumer.name}}
        image: "{{ .Values.deploy.consumer.image.repository }}:{{ .Values.deploy.consumer.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.deploy.consumer.image.pullPolicy }}
        env:
          - name: MYSQL_URL
            value: "{{ .Values.deploy.env.mysql }}"
          - name: MYSQL_PORT
            value: "{{ .Values.deploy.env.mysqlport }}"
          - name: KAFKA_HOST
            value: "{{ .Values.deploy.env.kafkahost }}"
          - name: KAFKA_PORT
            value: "{{ .Values.deploy.env.kafkaport }}"
          - name: TOPIC_NAME
            value: "{{ .Values.deploy.env.topicname }}"
          - name: REDIS_HOST
            value: "{{ .Values.deploy.env.redishost }}"