apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.merlot.name }}
spec:
  replicas: {{ .Values.deploy.merlot.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.merlot.selector.matchLabels.app }}
  template:
    metadata:
      labels:
        app: {{.Values.deploy.merlot.selector.matchLabels.app }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deploy.merlot.image.repository }}:{{ .Values.deploy.merlot.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deploy.merlot.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deploy.merlot.containerPort }}
          env:
            - name: KAFKA_HOST
              value: "{{ .Values.deploy.env.kafkahost }}"
            - name: KAFKA_PORT
              value: "{{ .Values.deploy.env.kafkaport }}"
            - name: REDIS_HOST
              value: "{{ .Values.deploy.env.redishost }}"
            - name: PHASE
              value: "{{ .Values.deploy.dev.phase}}"
