apiVersion: v1
kind: Service
metadata:
  name: {{ include ".Values.service.merlot.name" . }}
  labels:
    {{- include "merlot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.merlot.type }}
  ports:
    - port: {{ .Values.service.merlot.port }}
      targetPort: {{ .Values.service.merlot.targetPort}}
      protocol: TCP
      name: http
  selector:
    {{- include ".Values.service.merlot.name" . | nindent 4 }}
