apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.static.name}}
spec:
  ports:
  - port: {{ .Values.service.static.port }}
    name: http
    targetPort: {{ .Values.service.static.targetPort }}
  selector:
    app: {{ .Values.service.static.selector.app }}