apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.cert.name}}
spec:
  ports:
  - port: {{ .Values.service.cert.port }}
    name: api
    targetPort: {{ .Values.service.cert.targetPort }}
  selector:
    app: {{ .Values.service.cert.selector.app }}