# Default values for merlot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  merlot: 2
  consumer: 40


imagePullSecrets:
  - name: regcred


deploy:
  env:
    kafkahost: 198.19.248.153
    kafkaport: 9092
    redishost: 198.19.226.35
    mysql: dev.ceteris.co.kr
    mysqlport: 10005
    topicname: stocktest40
  merlot:
    name: merlotdeploy
    replicaCount: 2
    image:
      repository: purple-registry.kr.ncr.ntruss.com/merlot
      pullPolicy: IfNotPresent
      tag: "dev1"
    selector:
      matchLabels:
        app: merlot
    containerPort: 8000

  consumer:
    name: stock-consumer
    replicaCount: 3
    image:
      repository: purple-registry.kr.ncr.ntruss.com/youngjaikwon/purple_consumer
      pullPolicy: Always
      tag: "changed1"


#imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  merlot:
    name: merlot-svc
    type: ClusterIP
    port: 5000
    targetPort: 8000
    selector: merlot



ingress:
  enabled: false
  name: "juit-ingress"
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: juit.api.com
      paths:
        - path: /api
          backend:
            serviceName: merlot-svc
            servicePort: 5000
        - path: /prometheus
          backend:
            serviceName: yj-prom-kube-prometheus-st-prometheus
            servicePort: 9090
        - path: /grafana
          backend:
            serviceName: yj-prom-grafana
            servicePort: 80

  tls:
    - hosts:
        - juit.api.com
      secretName: devtls




autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
