# Default values for merlot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  merlot: 2
  consumer: 40


imagePullSecrets:
  - name: regcred


deploy:
  env:
    kafkahost: 198.19.248.153
    kafkaport: 9092
    redishost: 198.19.226.35
    mysql: dev.ceteris.co.kr
    mysqlport: 10005
    topicname: stocktest40
    phase: dev

  merlot:
    name: merlotdeploy
    replicaCount: 1
    image:
      repository: purple-registry.kr.ncr.ntruss.com/youngjai_kwon/merlot_kube
      pullPolicy: IfNotPresent
      tag: "real3"
    selector:
      matchLabels:
        app: merlot
    containerPort: 8000

  static:
    name: static-deploy
    replicaCount: 1
    selector:
      matchLabels:
        app: static-server
    image:
      repository: purple-registry.kr.ncr.ntruss.com/youngjai_kwon/static_server
      pullPolicy: IfNotPresent
      tag: "test1"
    containerPort: 80

  consumer:
    name: stock-consumer
    replicaCount: 10
    image:
      repository: purple-registry.kr.ncr.ntruss.com/youngjaikwon/purple_consumer
      pullPolicy: Always
      tag: "real3"

  cert:
    name: cert
    replicaCount: 1
    image:
      repository: purple-registry.kr.ncr.ntruss.com/youngjai_kwon/cert
      pullPolicy: Always
      tag: "test1"
    containerPort: 8080
  verif:
    name: verif
    replicaCount: 1
    image:
      repository: purple-registry.kr.ncr.ntruss.com/youngjai_kwon/verif
      pullPolicy: Always
      tag: "test1"
    containerPort: 8080


#imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  merlot:
    name: merlot-svc
    type: ClusterIP
    port: 5000
    targetPort: 8000
    selector: merlot
  cert:
    name: cert-svc
    port: 443
    targetPort: 8080
    selector:
      app: cert
  verif:
    name: verif-svc
    port: 442
    targetPort: 8080
    selector:
      app: verif
  static:
    name: static-svc
    port: 4999
    targetPort: 80
    selector:
      app: static-server

ingress:
  enabled: false
  name: "juit-ingress"
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: dev.ceteris.co.kr
      paths:
        - path: /api
          backend:
            serviceName: merlot-svc
            servicePort: 5000
        - path: /prometheus
          backend:
            serviceName: yj-prom-kube-prometheus-st-prometheus
            servicePort: 9090
        - path: /grafana
          backend:
            serviceName: yj-prom-grafana
            servicePort: 80
        - path: /verif
          backend:
            serviceName: verif-svc
            servicePort: 442
        - path: /cert
          backend:
            serviceName: cert-svc
            servicePort: 443
        - path: /static
          backend:
            serviceName: static-svc
            servicePort: 4999

  tls:
    - hosts:
        - dev.ceteris.co.kr
      secretName: devtls




autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
