apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: kafka-consumer-app
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka-consumer-app
    spec:
      containers:
        - name: kafka-consumer
          image: docker.io/youngjaikwon/kafka-consumer:test1
          imagePullPolicy: Always
          command: ["python3"]
          args: ["/engine/consumer_k8s.py", "--topicname" ,"test1", "--redishost", "198.19.157.154", "--kafkahost", "198.19.226.186:9092"]
