]apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka-consumer-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: kafka-consumer-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: kafka-consumer-app
    spec:
      containers:
        - name: kafka-consumer
          image: docker.io/youngjaikwon/kafka-consumer:test1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
