apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yj-kafka-metrics
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: juit-dev-prom
    app.kubernetes.io/managed-by: helm
    release: juit-dev-prom

spec:
  jobLabel: jobLabel

  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
  endpoints:
    - port: http-metrics
      path: "/metrics"
      interval: "30s"
  namespaceSelector:
    matchNames:
    - "default"